CREATE TABLE TEACHER(
	t_id				INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	employee_id			INT,

	CONSTRAINT FK_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES EMPLOYEE(e_id)
								ON DELETE SET NULL		ON UPDATE CASCADE
);
CREATE TABLE SCHEDULE(
	s_id				INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	teacher_id			INT,
	s_to				DATETIMEOFFSET NOT NULL,
	s_from				DATETIMEOFFSET NOT NULL,

	CONSTRAINT FK_TEACHER FOREIGN KEY (teacher_id) REFERENCES TEACHER(t_id)
);
CREATE TABLE STUDENT_DETAIL(
	sd_id				INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	first_name			VARCHAR(20) NOT NULL,
	last_name			VARCHAR(20) NOT NULL,
	sd_address			VARCHAR(50),
	email				VARCHAR(20),
	birth_date			DATE,
	phone_number		VARCHAR(10)
);
CREATE TABLE STUDENT_PURCHASE_HIST(
	sph_id				INT NOT NULL IDENTITY(1,1) PRIMARY KEY,	
	student_id			INT,
	enroll_detail_id	INT,
	sph_start_date		DATETIMEOFFSET NOT NULL,
	sph_end_date		DATETIMEOFFSET NOT NULL,

	CONSTRAINT FK_STUDENT FOREIGN KEY (student_id) REFERENCES STUDENT(s_id)
									ON DELETE SET NULL		ON UPDATE CASCADE,
	CONSTRAINT FK_ENROLLMENT FOREIGN KEY (enroll_detail_id) REFERENCES ENROLLMENT_DETAIL(e_detail_id)
);
CREATE TABLE STUDENT(
	s_id				INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	first_name			VARCHAR(20),
	last_name			VARCHAR(20),
	stud_detail_id		INT,

	CONSTRAINT FK_DETAIL FOREIGN KEY (stud_detail_id) REFERENCES STUDENT_DETAIL(sd_id)
								ON DELETE SET NULL			ON UPDATE CASCADE
);