CREATE TABLE COURSE(
	c_id					INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	c_description			VARCHAR(50)
);
CREATE TABLE LESSON(
	less_id					INT NOT NULL PRIMARY KEY,
	less_type				VARCHAR(10) NOT NULL CHECK (less_type = 'priv' OR less_type = 'group' OR less_type = 'pract'),
	duration				TIME,
	cost					MONEY,
	course_id				INT,

	CONSTRAINT FK_COURSE FOREIGN KEY (course_id) REFERENCES COURSE(c_id)
									ON DELETE SET NULL		ON UPDATE CASCADE
);
CREATE TABLE MANAGEMENT(
	mgmnt_id				INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	first_name				VARCHAR(20),
	last_name				VARCHAR(20)
);
CREATE TABLE ENROLLMENT(
	enroll_id				INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	enroll_date				DATETIMEOFFSET DEFAULT GETDATE(),
	management_id			INT,

	CONSTRAINT FK_MANAGMENT FOREIGN KEY (management_id) REFERENCES MANAGEMENT(mgmnt_id)
									ON DELETE SET NULL		ON UPDATE CASCADE
);
CREATE TABLE ENROLLMENT_DETAIL(
	e_detail_id				INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	enrollment_id			INT,
	student_id				INT,
	course_id				INT,
	private_course			INT NOT NULL,
	group_course			INT NOT NULL,
	practice_course			INT NOT NULL,
	supervisor_id			INT,
	teacher_id				INT,
	enroll_date				DATETIMEOFFSET DEFAULT GETDATE(),

	CONSTRAINT FK_ENROLLMENT FOREIGN KEY (enrollment_id) REFERENCES ENROLLMENT(enroll_id)
																ON UPDATE CASCADE,
	CONSTRAINT FK_STUDENT FOREIGN KEY (student_id) REFERENCES STUDENT(s_id)
																ON UPDATE CASCADE,
	CONSTRAINT FK_COURSE FOREIGN KEY (course_id) REFERENCES COURSE(c_id)
																ON UPDATE CASCADE,
	CONSTRAINT FK_SUPERVISOR FOREIGN KEY (supervisor_id) REFERENCES MANAGEMENT(mgmnt_id)
																ON UPDATE CASCADE,
	CONSTRAINT FK_TEACHER FOREIGN KEY (teacher_id) REFERENCES TEACHER(t_id)
																ON UPDATE CASCADE,
);
CREATE TABLE STUDENT_PURCHASE_HIST(
	sph_id					INT NOT NULL IDENTITY(1,1) PRIMARY KEY,	
	student_id				INT,
	enroll_detail_id		INT,
	sph_start_date			DATETIMEOFFSET NOT NULL,
	sph_end_date			DATETIMEOFFSET NOT NULL,

	CONSTRAINT FK_STUDENT FOREIGN KEY (student_id) REFERENCES STUDENT(s_id)
									ON DELETE SET NULL		ON UPDATE CASCADE,
	CONSTRAINT FK_ENROLLMENT FOREIGN KEY (enroll_detail_id) REFERENCES ENROLLMENT_DETAIL(e_detail_id)
);
CREATE TABLE APPOINTMENT(
	app_id					INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	date_created			DATETIMEOFFSET NOT NULL,
	teacher_id				INT,
	teacher_name			VARCHAR(20),
	student_id				INT,
	student_name			VARCHAR(20),
	start_time				DATETIMEOFFSET,
	end_time				DATETIMEOFFSET,
	course_id				INT,
	lesson_id				INT,
	canceled				BIT,
	cancel_reason			TEXT,

	CONSTRAINT FK_TEACHER FOREIGN KEY (teacher_id) REFERENCES TEACHER(t_id)
									ON DELETE SET NULL		ON UPDATE CASCADE,
	CONSTRAINT FK_STUDENT FOREIGN KEY (student_id) REFERENCES STUDENT(s_id)
									ON DELETE SET NULL		ON UPDATE CASCADE,
	CONSTRAINT FK_COURSE FOREIGN KEY (course_id) REFERENCES COURSE(c_id)
									ON DELETE SET NULL		ON UPDATE CASCADE,
	CONSTRAINT FK_LESSON_TYPE FOREIGN KEY (lesson_id) REFERENCES LESSON(less_id)
									ON DELETE SET NULL		ON UPDATE CASCADE
);
CREATE TABLE LESSON_TAKEN(
	taken_id				INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	appointment_id			INT,
	course_id				INT,
	lesson_id				INT,

	CONSTRAINT FK_APPOINTMENT FOREIGN KEY (appointment_id) REFERENCES APPOINTMENT(app_id)
									ON DELETE SET NULL		ON UPDATE CASCADE,
	CONSTRAINT FK_COURSE FOREIGN KEY (course_id) REFERENCES COURSE(c_id)
									ON DELETE SET NULL		ON UPDATE CASCADE,
	CONSTRAINT FK_LESSON FOREIGN KEY (lesson_id) REFERENCES LESSON(less_id)
									ON DELETE SET NULL		ON UPDATE CASCADE
);
CREATE TABLE LESSON_DETAIL(
	detail_id				INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	course_id				INT,
	lesson_id				INT,
	duration				TIME,

	CONSTRAINT FK_COURSE FOREIGN KEY (course_id) REFERENCES COURSE(c_id)
									ON DELETE SET NULL		ON UPDATE CASCADE,
	CONSTRAINT FK_LESSON FOREIGN KEY (lesson_id) REFERENCES LESSON(less_id)
									ON DELETE SET NULL		ON UPDATE CASCADE
);
CREATE TABLE LESSON_BOOKED(
	booked_id				INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	appointment_id			INT,
	course_id				INT,
	lesson_id				INT,

	CONSTRAINT FK_APPOINTMENT FOREIGN KEY (appointment_id) REFERENCES APPOINTMENT(app_id)
									ON DELETE SET NULL		ON UPDATE CASCADE,
	CONSTRAINT FK_COURSE FOREIGN KEY (course_id) REFERENCES COURSE(c_id)
									ON DELETE SET NULL		ON UPDATE CASCADE,
	CONSTRAINT FK_LESSON FOREIGN KEY (lesson_id) REFERENCES LESSON(less_id)
									ON DELETE SET NULL		ON UPDATE CASCADE
);
CREATE TABLE STUD_PRIV_LESS_TAKEN(
	splt_id					INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	splr_id					INT NOT NULL,
	scheduled_priv_date		DATETIMEOFFSET DEFAULT GETDATE(),
	lesson_taken_id			INT,
	total_course_pt			INT,

	CONSTRAINT FK_LESSON_TAKEN FOREIGN KEY (lesson_taken_id) REFERENCES LESSON_TAKEN(taken_id)
									ON DELETE SET NULL		ON UPDATE CASCADE
);
CREATE TABLE STUD_PRIV_LESS_REMAIN(
	splr_id					INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	splt_id					INT NOT NULL,
	student_id				INT,
	enroll_detail_id		INT,
	tcpr_id					INT,

	CONSTRAINT FK_STUDENT FOREIGN KEY (student_id) REFERENCES STUDENT(s_id)
									ON DELETE SET NULL		ON UPDATE CASCADE,
	CONSTRAINT FK_ENROLL_DETAIL FOREIGN KEY (enroll_detail_id) REFERENCES ENROLLMENT_DETAIL(e_detail_id)
									ON DELETE SET NULL		ON UPDATE CASCADE,
	CONSTRAINT FK_LESSON_TAKEN FOREIGN KEY (splt_id) REFERENCES STUD_PRIV_LESS_TAKEN(splt_id)
									ON DELETE SET NULL		ON UPDATE CASCADE,
);