INSERT INTO VENDOR (v_id, v_name, v_location) VALUES (1,'Brainsphere','50574 Corry Pass','Johnstown','PA'),
(2,'Eadel','5167 Corry Avenue','San Francisco','CA'),
(3,'Skibox','6 Melby Road','Sacramento','CA'),
(4,'Skiptube','0383 Hansons Trail','Long Beach','CA'),
(5,'Youopia','9 Kim Drive','Jamaica','NY'),
(6,'Youspan','030 Orin Place','Hollywood','FL'),
(7,'Kwideo','38 Charing Cross Place','Atlanta','GA'),
(8,'Mita','721 Linden Place','San Antonio','TX'),
(9,'Flashpoint','02623 5th Hill','Duluth','GA'),
(10,'Zooxo','3035 Vidon Point','Savannah','GA'),
(11,'Pixoboo','789 Cordelia Crossing','Camden','NJ'),
(12,'Rhycero','9827 Summit Parkway','Topeka','KS'),
(13,'Cogilith','13 Straubel Street','Kent','WA'),
(14,'Yakijo','2 Raven Way','Charlotte','NC'),
(15,'Realblab','79426 Darwin Lane','Tulsa','OK'),
(16,'Zoomcast','4 Hollow Ridge Drive','Fairbanks','AK'),
(17,'Bluezoom','39 Birchwood Drive','Fort Worth','TX'),
(18,'Skyble','8922 Moose Place','Portland','OR'),
(19,'Geba','03890 West Plaza','Philadelphia','PA'),
(20,'Feedmix','9 Mayer Road','Eugene','OR');
